const mockBoard = [
  [
    {
      id: { x: 0, y: 0 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 2,
    },
    {
      id: { x: 0, y: 1 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 2,
    },
    {
      id: { x: 0, y: 2 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 0, y: 3 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 0,
    },
    {
      id: { x: 0, y: 4 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 0,
    },
  ],
  [
    {
      id: { x: 1, y: 0 },
      isMine: true,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 1, y: 1 },
      isMine: true,
      isClicked: false,
      isFlag: false,
      surroundingMines: 2,
    },
    {
      id: { x: 1, y: 2 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 2,
    },
    {
      id: { x: 1, y: 3 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 1, y: 4 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 0,
    },
  ],
  [
    {
      id: { x: 2, y: 0 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 2,
    },
    {
      id: { x: 2, y: 1 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 3,
    },
    {
      id: { x: 2, y: 2 },
      isMine: true,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 2, y: 3 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 2, y: 4 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 0,
    },
  ],
  [
    {
      id: { x: 3, y: 0 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 3, y: 1 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 2,
    },
    {
      id: { x: 3, y: 2 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 3, y: 3 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 2,
    },
    {
      id: { x: 3, y: 4 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
  ],
  [
    {
      id: { x: 4, y: 0 },
      isMine: true,
      isClicked: false,
      isFlag: false,
      surroundingMines: 0,
    },
    {
      id: { x: 4, y: 1 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 4, y: 2 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 0,
    },
    {
      id: { x: 4, y: 3 },
      isMine: false,
      isClicked: false,
      isFlag: false,
      surroundingMines: 1,
    },
    {
      id: { x: 4, y: 4 },
      isMine: true,
      isClicked: false,
      isFlag: false,
      surroundingMines: 0,
    },
  ],
];

export default mockBoard;
